### ISSUE TITLE
Next.js + responsive config

### ISSUE THREAD

**Issue by maor-benami** [maxmarinich/react-alice-carousel#214]
my usecase:

```jsx
<AliceCarousel
    disableDotsControls
    items={articles.map((article, i) => {
        return (
            <Article key={i} article={article} />
        )
    })}
    responsive={{
        0: { items: 1 },
        768: { items: 2 }
    }}
    paddingRight={100}
/>
```

the error:

```
react-dom.development.js?ac89:67 Warning: Prop `className` did not match. Server: "alice-carousel__stage-item" Client: "alice-carousel__stage-item __active"
    at li
    at exports.StageItem (webpack-internal:///./node_modules/react-alice-carousel/lib/views/StageItem.js:1:288)
    at ul
    at div
    at div
    at div
    at t (webpack-internal:///./node_modules/react-alice-carousel/lib/react-alice-carousel.js:1:3489)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-99289b21.browser.esm.js:55:66)
    at ArticleSlider (webpack-internal:///./components/landa/ArticleSlider/ArticleSlider.tsx:225:60)
    at Home (webpack-internal:///./containers/Home/Home.tsx:18:23)
    at Index (webpack-internal:///./pages/index.tsx:19:23)
    at MyApp (webpack-internal:///./pages/_app.tsx:39:27)
    at StyleRegistry (webpack-internal:///./node_modules/styled-jsx/dist/stylesheet-registry.js:231:34)
    at ErrorBoundary (webpack-internal:///./node_modules/@next/react-dev-overlay/lib/internal/ErrorBoundary.js:26:47)
    at ReactDevOverlay (webpack-internal:///./node_modules/@next/react-dev-overlay/lib/internal/ReactDevOverlay.js:90:23)
    at Container (webpack-internal:///./node_modules/next/dist/client/index.js:305:9)
    at AppContainer (webpack-internal:///./node_modules/next/dist/client/index.js:745:26)
    at Root (webpack-internal:///./node_modules/next/dist/client/index.js:866:27)
printWarning @ react-dom.development.js?ac89:67
error @ react-dom.development.js?ac89:43
warnForPropDifference @ react-dom.development.js?ac89:8824
diffHydratedProperties @ react-dom.development.js?ac89:9645
hydrateInstance @ react-dom.development.js?ac89:10400
prepareToHydrateHostInstance @ react-dom.development.js?ac89:14616
completeWork @ react-dom.development.js?ac89:19458
completeUnitOfWork @ react-dom.development.js?ac89:22815
performUnitOfWork @ react-dom.development.js?ac89:22787
workLoopSync @ react-dom.development.js?ac89:22707
renderRootSync @ react-dom.development.js?ac89:22670
performSyncWorkOnRoot @ react-dom.development.js?ac89:22293
scheduleUpdateOnFiber @ react-dom.development.js?ac89:21881
updateContainer @ react-dom.development.js?ac89:25482
eval @ react-dom.development.js?ac89:26021
unbatchedUpdates @ react-dom.development.js?ac89:22431
legacyRenderSubtreeIntoContainer @ react-dom.development.js?ac89:26020
hydrate @ react-dom.development.js?ac89:26086
renderReactElement @ index.js?46cb:488
doRender @ index.js?46cb:709
_callee$ @ index.js?46cb:384
tryCatch @ runtime.js?2d8a:45
invoke @ runtime.js?2d8a:274
prototype.<computed> @ runtime.js?2d8a:97
asyncGeneratorStep @ index.js?46cb:31
_next @ index.js?46cb:49
eval @ index.js?46cb:54
eval @ index.js?46cb:46
_render @ index.js?46cb:403
render @ index.js?46cb:406
eval @ next-dev.js?3515:76
eval @ fouc.js?0087:12
requestAnimationFrame (async)
displayContent @ fouc.js?0087:7
eval @ next-dev.js?3515:75
Promise.then (async)
eval @ next-dev.js?3515:38
./node_modules/next/dist/client/next-dev.js @ main.js?ts=1636182696516:578
options.factory @ webpack.js?ts=1636182696516:633
__webpack_require__ @ webpack.js?ts=1636182696516:37
__webpack_exec__ @ main.js?ts=1636182696516:1247
(anonymous) @ main.js?ts=1636182696516:1248
webpackJsonpCallback @ webpack.js?ts=1636182696516:1179
(anonymous) @ main.js?ts=1636182696516:9
Show 2 more frames

```

note: if i remove the responsive config the error disappears

**Comment by maxmarinich** [comment]
Hi, @maor-benami! Please look #183 & #210. I guess you checked this issue in the browser with default mode (where client `innerWidth` more than 768 pxs). When SSR used,  window `innerWidth` not applying and the lib use `0` value by default. 
You can: 
- set gallery [property](https://github.com/maxmarinich/react-alice-carousel#options) `innerWidth=768`
- check behavior in mobile mode with device which width less than 768 pxs
