### ISSUE TITLE
Having trouble adding as git dependency, build is failing: webpack is not found 

### ISSUE THREAD

**Issue by madsaylor** [maxmarinich/react-alice-carousel#47]
I forked your repo, and tried to add it as git dependency at package.json at create-react-app, added install script to being run after install, similar to build:lib.
It fails, unable to locate webpack:
```
>react-alice-carousel@1.13.0 install /Users/madsaylor/Projects/new_realty/node_modules/react-alice-carousel
>webpack --config webpack.lib.config.js --colors
internal/modules/cjs/loader.js:583
    throw err;
    ^
Error: Cannot find module 'webpack'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/madsaylor/Projects/new_realty/node_modules/react-alice-carousel/webpack.lib.config.js:2:17)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
```

Any ways to avoid that?
Thanks for you work

**Comment by maxmarinich** [comment]
@madsaylor, you should change path to the lib in the `package.json` form `"main": "./lib/react-alice-carousel"` to `"main": "app/components/react-alice-carousel"` or create `lib/react-alice-carousel` directory.

**Comment by madsaylor** [comment]
Including it, as is, without building, fails as create-react-app do not support class properties considering it as experimental feature

**Comment by maxmarinich** [comment]
then you should create directory `lib/react-alice-carousel` with a compiled code supporting by your boilerplate. To create `npm lib` a'm not use the repo builder. Maybe soon i'll improve the last.
